package:
  name: batch-iv-analysis
  version: "2.7.1"

source:
  git_rev: v2.7.1
  git_url: https://github.com/greysAcademicCode/batch-iv-analysis.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python [3.6]
    - numpy
    - scipy
    - pyqt5
    - sympy

test:
  imports:
    - batch_iv_analysis

about:
  home: https://github.com/greysAcademicCode/batch-iv-analysis
  license: MIT
  license_file: LICENSE.txt
