package:
  name: mutovis-analysis
  version: "3.0.0" # make sure this matches github build tag when doing release

source:
  path: .
  #git_rev: v2.9.1  # use this for relesase build from github tag
  git_url: https://github.com/mutovis/analysis-software

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - pyqt
    - sympy
    - matplotlib
    - mpmath
    - gmpy2
    - dill
    - python.app  # [osx]
    - lmfit
    - h5py
    - uncertainties

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch_python: True
  entry_points:
          - mutovis-analysis = batch_iv_analysis:main
  osx_is_app: True

test:
  imports:
    - batch_iv_analysis

app:
  entry: mutovis-analysis
  icon: misc/icon.png
  summary: Solar cell I-V data fitter
  type: desk

about:
  home: https://github.com/mutovis/analysis-software
  license: GPL-3.0
  license_file: LICENSE
  summary: Solar cell I-V data fitter
