package:
  name: batch-iv-analysis
  version: "2.9.0"

source:
  #path: .
  git_rev: v2.9.0
  git_url: https://github.com/greysAcademicCode/batch-iv-analysis.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - pyqt
    - sympy
    - matplotlib
    - mpmath
    - gmpy2
    - dill
    - python.app  # [osx]


build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch_python: True
  entry_points:
          - batch-iv-analysis = batch_iv_analysis:main
  osx_is_app: True

test:
  imports:
    - batch_iv_analysis

app:
  entry: batch-iv-analysis
  icon: icon.png
  summary: Solar cell I-V data fitter
  type: desk

about:
  home: https://github.com/greysAcademicCode/batch-iv-analysis
  license: MIT
  license_file: LICENSE.txt
  summary: Solar cell I-V data fitter
