{% set version = "3.0.7" %}
#{% set sha256 = "77520850ae21620ec31738f4a7b467acaa44de6d3752d8ac7a9f4dcf55d77853" %}

package:
  name: mutovis-analysis
  version: "{{ version }}"

source:
  path: .
  #url: https://github.com/mutovis/analysis-software/archive/v{{ version }}.tar.gz
  #sha256: "{{ sha256 }}"

requirements:
  host:
    - python >=3.4
    - setuptools
  run:
    - python >=3.4
    - h5py
    - numpy
    - scipy
    - sympy
    - matplotlib
    - mpmath
    - gmpy2
    - dill
    - lmfit
    - uncertainties
    - python.app  # [osx]
    - pyqt
    - packaging

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python
  entry_points:
          - mutovis-analysis = batch_iv_analysis.__main__:main
  osx_is_app: True

test:
  imports:
    - batch_iv_analysis

app:
  entry: mutovis-analysis
  icon: misc/icon.png
  summary: Solar cell I-V data fitter
  type: desk

about:
  home: https://github.com/mutovis/analysis-software
  license: GPL-3.0
  license_file: LICENSE
  summary: Solar cell I-V data fitter
