package:
  name: batch-iv-analysis
  version: "3.0.0" # make sure this matches github build tag when doing release

source:
  path: .
  #git_rev: v2.9.1  # use this for relesase build from github tag
  git_url: https://github.com/greysAcademicCode/batch-iv-analysis.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - pyqt
    - sympy
    - matplotlib
    - mpmath
    - gmpy2
    - dill
    - python.app  # [osx]
    - hdf5
    - lmfit

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch_python: True
  entry_points:
          - batch-iv-analysis = batch_iv_analysis:main
  osx_is_app: True

test:
  imports:
    - batch_iv_analysis

app:
  entry: batch-iv-analysis
  icon: misc/icon.png
  summary: Solar cell I-V data fitter
  type: desk

about:
  home: https://github.com/greysAcademicCode/batch-iv-analysis
  license: MIT
  license_file: LICENSE.txt
  summary: Solar cell I-V data fitter
