package:
  name: batch-iv-analysis
  version: "2.7.2"

source:
  path: .
#  git_rev: v2.7.2
#  git_url: https://github.com/greysAcademicCode/batch-iv-analysis.git

requirements:
  build:
    - python [3.6]
    - setuptools
  run:
    - python [3.6]
    - numpy
    - scipy
    - pyqt
    - sympy
    - matplotlib
    - mpmath

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch_python: True
  entry_points:
    - batch-iv-analysis = batch_iv_analysis:main

test:
  imports:
    - batch_iv_analysis

app:
#  entry: python -m batch_iv_analysis batch_iv_analysis    [win]
#  entry: python -m batch_iv_analysis batch_iv_analysis    [linux]
  entry: batch-iv-analysis
  icon: icon.png
  summary: Solar cell I-V data fitting
  type: desk

about:
  home: https://github.com/greysAcademicCode/batch-iv-analysis
  license: MIT
  license_file: LICENSE.txt
