package:
  name: batch-iv-analysis
  version: "2.7.2"

source:
  git_rev: v2.7.2
  git_url: https://github.com/greysAcademicCode/batch-iv-analysis.git

requirements:
  build:
    - python [3.6]
    - setuptools
  run:
    - python [3.6]
    - numpy
    - scipy
    - pyqt
    - sympy
    - matplotlib

build:
  number: 0
  script: python setup.py install
  noarch_python: True

test:
  imports:
    - batch_iv_analysis

about:
  home: https://github.com/greysAcademicCode/batch-iv-analysis
  license: MIT
  license_file: LICENSE.txt
