package:
  name: batch-iv-analysis
  version: "2.7.2"

source:
  path: .
#  git_rev: v2.7.2
#  git_url: https://github.com/greysAcademicCode/batch-iv-analysis.git

requirements:
  build:
    - python [3.6]
    - setuptools
  run:
    - python [3.6]
    - numpy
    - scipy
    - pyqt
    - sympy
    - matplotlib
    - mpmath

build:
  number: 0
  script: python setup.py install
  noarch_python: True

test:
  imports:
    - batch_iv_analysis

app:
  entry: batch_iv_analysis .    [win]
  entry: batch_iv_analysis .    [linux]
  icon: icon.ico
  summary: solar cell I-V data fitting

about:
  home: https://github.com/greysAcademicCode/batch-iv-analysis
  license: MIT
  license_file: LICENSE.txt
